/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVendasRelatorioRouteImport } from './routes/_authenticated/vendas-relatorio'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated/vendas'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedServicoFunerarioRouteImport } from './routes/_authenticated/servico-funerario'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedRecebimentoRouteImport } from './routes/_authenticated/recebimento'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedEmpresaFinanceiroRouteImport } from './routes/_authenticated/empresa-financeiro'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedContasRouteImport } from './routes/_authenticated/contas'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAssociadosListaRouteImport } from './routes/_authenticated/associados-lista'
import { Route as AuthenticatedAssociadosRouteImport } from './routes/_authenticated/associados'
import { Route as ApiPublicWebhooksCobrancaProvedorRouteImport } from './routes/api/public/webhooks/cobranca.$provedor'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendasRelatorioRoute =
  AuthenticatedVendasRelatorioRouteImport.update({
    id: '/vendas-relatorio',
    path: '/vendas-relatorio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicoFunerarioRoute =
  AuthenticatedServicoFunerarioRouteImport.update({
    id: '/servico-funerario',
    path: '/servico-funerario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecebimentoRoute =
  AuthenticatedRecebimentoRouteImport.update({
    id: '/recebimento',
    path: '/recebimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresaFinanceiroRoute =
  AuthenticatedEmpresaFinanceiroRouteImport.update({
    id: '/empresa-financeiro',
    path: '/empresa-financeiro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContasRoute = AuthenticatedContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssociadosListaRoute =
  AuthenticatedAssociadosListaRouteImport.update({
    id: '/associados-lista',
    path: '/associados-lista',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssociadosRoute = AuthenticatedAssociadosRouteImport.update({
  id: '/associados',
  path: '/associados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWebhooksCobrancaProvedorRoute =
  ApiPublicWebhooksCobrancaProvedorRouteImport.update({
    id: '/api/public/webhooks/cobranca/$provedor',
    path: '/api/public/webhooks/cobranca/$provedor',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/associados': typeof AuthenticatedAssociadosRoute
  '/associados-lista': typeof AuthenticatedAssociadosListaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contas': typeof AuthenticatedContasRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresa-financeiro': typeof AuthenticatedEmpresaFinanceiroRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/recebimento': typeof AuthenticatedRecebimentoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/servico-funerario': typeof AuthenticatedServicoFunerarioRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/vendas-relatorio': typeof AuthenticatedVendasRelatorioRoute
  '/api/public/webhooks/cobranca/$provedor': typeof ApiPublicWebhooksCobrancaProvedorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/associados': typeof AuthenticatedAssociadosRoute
  '/associados-lista': typeof AuthenticatedAssociadosListaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contas': typeof AuthenticatedContasRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresa-financeiro': typeof AuthenticatedEmpresaFinanceiroRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/recebimento': typeof AuthenticatedRecebimentoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/servico-funerario': typeof AuthenticatedServicoFunerarioRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/vendas-relatorio': typeof AuthenticatedVendasRelatorioRoute
  '/api/public/webhooks/cobranca/$provedor': typeof ApiPublicWebhooksCobrancaProvedorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/associados': typeof AuthenticatedAssociadosRoute
  '/_authenticated/associados-lista': typeof AuthenticatedAssociadosListaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contas': typeof AuthenticatedContasRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/empresa-financeiro': typeof AuthenticatedEmpresaFinanceiroRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/recebimento': typeof AuthenticatedRecebimentoRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/servico-funerario': typeof AuthenticatedServicoFunerarioRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
  '/_authenticated/vendas-relatorio': typeof AuthenticatedVendasRelatorioRoute
  '/api/public/webhooks/cobranca/$provedor': typeof ApiPublicWebhooksCobrancaProvedorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/associados'
    | '/associados-lista'
    | '/configuracoes'
    | '/contas'
    | '/crm'
    | '/dashboard'
    | '/empresa-financeiro'
    | '/financeiro'
    | '/planos'
    | '/recebimento'
    | '/relatorios'
    | '/servico-funerario'
    | '/usuarios'
    | '/vendas'
    | '/vendas-relatorio'
    | '/api/public/webhooks/cobranca/$provedor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/associados'
    | '/associados-lista'
    | '/configuracoes'
    | '/contas'
    | '/crm'
    | '/dashboard'
    | '/empresa-financeiro'
    | '/financeiro'
    | '/planos'
    | '/recebimento'
    | '/relatorios'
    | '/servico-funerario'
    | '/usuarios'
    | '/vendas'
    | '/vendas-relatorio'
    | '/api/public/webhooks/cobranca/$provedor'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/associados'
    | '/_authenticated/associados-lista'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contas'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/empresa-financeiro'
    | '/_authenticated/financeiro'
    | '/_authenticated/planos'
    | '/_authenticated/recebimento'
    | '/_authenticated/relatorios'
    | '/_authenticated/servico-funerario'
    | '/_authenticated/usuarios'
    | '/_authenticated/vendas'
    | '/_authenticated/vendas-relatorio'
    | '/api/public/webhooks/cobranca/$provedor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicWebhooksCobrancaProvedorRoute: typeof ApiPublicWebhooksCobrancaProvedorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendas-relatorio': {
      id: '/_authenticated/vendas-relatorio'
      path: '/vendas-relatorio'
      fullPath: '/vendas-relatorio'
      preLoaderRoute: typeof AuthenticatedVendasRelatorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servico-funerario': {
      id: '/_authenticated/servico-funerario'
      path: '/servico-funerario'
      fullPath: '/servico-funerario'
      preLoaderRoute: typeof AuthenticatedServicoFunerarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recebimento': {
      id: '/_authenticated/recebimento'
      path: '/recebimento'
      fullPath: '/recebimento'
      preLoaderRoute: typeof AuthenticatedRecebimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresa-financeiro': {
      id: '/_authenticated/empresa-financeiro'
      path: '/empresa-financeiro'
      fullPath: '/empresa-financeiro'
      preLoaderRoute: typeof AuthenticatedEmpresaFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contas': {
      id: '/_authenticated/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof AuthenticatedContasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/associados-lista': {
      id: '/_authenticated/associados-lista'
      path: '/associados-lista'
      fullPath: '/associados-lista'
      preLoaderRoute: typeof AuthenticatedAssociadosListaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/associados': {
      id: '/_authenticated/associados'
      path: '/associados'
      fullPath: '/associados'
      preLoaderRoute: typeof AuthenticatedAssociadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/cobranca/$provedor': {
      id: '/api/public/webhooks/cobranca/$provedor'
      path: '/api/public/webhooks/cobranca/$provedor'
      fullPath: '/api/public/webhooks/cobranca/$provedor'
      preLoaderRoute: typeof ApiPublicWebhooksCobrancaProvedorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssociadosRoute: typeof AuthenticatedAssociadosRoute
  AuthenticatedAssociadosListaRoute: typeof AuthenticatedAssociadosListaRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContasRoute: typeof AuthenticatedContasRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmpresaFinanceiroRoute: typeof AuthenticatedEmpresaFinanceiroRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedRecebimentoRoute: typeof AuthenticatedRecebimentoRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedServicoFunerarioRoute: typeof AuthenticatedServicoFunerarioRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
  AuthenticatedVendasRelatorioRoute: typeof AuthenticatedVendasRelatorioRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssociadosRoute: AuthenticatedAssociadosRoute,
  AuthenticatedAssociadosListaRoute: AuthenticatedAssociadosListaRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContasRoute: AuthenticatedContasRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmpresaFinanceiroRoute: AuthenticatedEmpresaFinanceiroRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedRecebimentoRoute: AuthenticatedRecebimentoRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedServicoFunerarioRoute: AuthenticatedServicoFunerarioRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
  AuthenticatedVendasRelatorioRoute: AuthenticatedVendasRelatorioRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicWebhooksCobrancaProvedorRoute:
    ApiPublicWebhooksCobrancaProvedorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
